(function() {
  'use strict';
  const { TIME_WORKED_SELECTORS, RETRY_DELAY, MAX_RETRIES, MAIN_IFRAME_SELECTOR } = window.inlineUI.constants;
  function getRecordTarget() { const params = new URLSearchParams(window.location.search); const direct = params.get('sysparm_record_target'); if (direct) return direct; const frame = document.querySelector(MAIN_IFRAME_SELECTOR); const src = frame?.getAttribute('src') || frame?.contentWindow?.location?.search; if (!src) return null; const qs = src.includes('?') ? src.split('?')[1] : src; return new URLSearchParams(qs).get('sysparm_record_target'); }
  function getDocumentContexts() { const contexts = [document]; Array.from(document.querySelectorAll('iframe')).forEach(frame => { try { if (frame.contentDocument) contexts.push(frame.contentDocument); } catch (_) {} }); const mainFrame = document.querySelector(MAIN_IFRAME_SELECTOR); if (mainFrame?.contentDocument && !contexts.includes(mainFrame.contentDocument)) contexts.push(mainFrame.contentDocument); return contexts; }
  function findTimeWorkedElement() { const target = getRecordTarget(); const contexts = getDocumentContexts(); const ordered = target === 'incident' ? [document.querySelector(MAIN_IFRAME_SELECTOR)?.contentDocument, ...contexts].filter(Boolean) : contexts; for (const ctx of ordered) { for (const selector of TIME_WORKED_SELECTORS) { const el = ctx.querySelector(selector); if (el) { const container = el.closest('.form-group') || el.parentElement; return { element: container || el, doc: ctx }; } } const label = Array.from(ctx.querySelectorAll('label')).find(l => (l.textContent || '').trim().toLowerCase().includes('time worked')); if (label) { const container = label.closest('.form-group') || label.parentElement; if (container) return { element: container, doc: ctx }; } } return null; }
  async function waitForTimeWorkedField(retries = 0) { const result = findTimeWorkedElement(); if (result) return result; if (retries >= MAX_RETRIES) { console.log('ServiceNow Time Assistant: Time Worked field not found after max retries'); return null; } await new Promise(resolve => setTimeout(resolve, RETRY_DELAY)); return waitForTimeWorkedField(retries + 1); }
  window.inlineUI.contexts = { getRecordTarget, getDocumentContexts, findTimeWorkedElement, waitForTimeWorkedField };
})();

